version: '3.4'

services:
  track-it:
    image: ${DOCKER_REGISTRY-}trackit
    build:
      context: .
      dockerfile: track-it/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000